### ISSUE TITLE
scrollspy

### ISSUE THREAD

**Issue by wzpan** [zanfab/gitbook-plugin-intopic-toc#6]
Is it possible to implement a scroll-spy like the ToC of gitbook V2 document?

https://docs.gitbook.com/v2-changes/important-differences

The most straight forward method I know is using Twitter Bootstrap. Here's an example:

https://afeld.github.io/bootstrap-toc/

Also there are many other alternatives. For example a jQuery based scenario: https://www.jqueryscript.net/menu/fixed-table-contents-scrollspy.html

**Comment by fzankl** [comment]
I've already started implementing a scrollspy functionality - hope it will be ready soon.

**Comment by fzankl** [comment]
Please have a look at PR #14 
With this PR I've implemented different layout modes along with improved scrollspy behavior.

Do these changes fit?
